package com.pojos;
// Generated Nov 14, 2018 4:08:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Announcementinfo generated by hbm2java
 */
public class Announcementinfo  implements java.io.Serializable {


     private Integer announcementId;
     private Departmentinfo departmentinfo;
     private Userinfo userinfo;
     private String type;
     private String importance;
     private String header;
     private String context;
     private Date startDate;
     private Date endDate;
     private String isActive;

    public Announcementinfo() {
    }

	
    public Announcementinfo(Departmentinfo departmentinfo, Userinfo userinfo, String type, String importance, String header, String context, Date startDate, String isActive) {
        this.departmentinfo = departmentinfo;
        this.userinfo = userinfo;
        this.type = type;
        this.importance = importance;
        this.header = header;
        this.context = context;
        this.startDate = startDate;
        this.isActive = isActive;
    }
    public Announcementinfo(Departmentinfo departmentinfo, Userinfo userinfo, String type, String importance, String header, String context, Date startDate, Date endDate, String isActive) {
       this.departmentinfo = departmentinfo;
       this.userinfo = userinfo;
       this.type = type;
       this.importance = importance;
       this.header = header;
       this.context = context;
       this.startDate = startDate;
       this.endDate = endDate;
       this.isActive = isActive;
    }
   
    public Integer getAnnouncementId() {
        return this.announcementId;
    }
    
    public void setAnnouncementId(Integer announcementId) {
        this.announcementId = announcementId;
    }
    public Departmentinfo getDepartmentinfo() {
        return this.departmentinfo;
    }
    
    public void setDepartmentinfo(Departmentinfo departmentinfo) {
        this.departmentinfo = departmentinfo;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getImportance() {
        return this.importance;
    }
    
    public void setImportance(String importance) {
        this.importance = importance;
    }
    public String getHeader() {
        return this.header;
    }
    
    public void setHeader(String header) {
        this.header = header;
    }
    public String getContext() {
        return this.context;
    }
    
    public void setContext(String context) {
        this.context = context;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }




}


