package com.pojos;
// Generated Nov 14, 2018 4:08:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departmentinfo generated by hbm2java
 */
public class Departmentinfo  implements java.io.Serializable {


     private Integer departmentInfoId;
     private String name;
     private Set<Userinfo> userinfos = new HashSet<Userinfo>(0);
     private Set<Announcementinfo> announcementinfos = new HashSet<Announcementinfo>(0);
     private Set<Subjectinfo> subjectinfos = new HashSet<Subjectinfo>(0);

    public Departmentinfo() {
    }

	
    public Departmentinfo(String name) {
        this.name = name;
    }
    public Departmentinfo(String name, Set<Userinfo> userinfos, Set<Announcementinfo> announcementinfos, Set<Subjectinfo> subjectinfos) {
       this.name = name;
       this.userinfos = userinfos;
       this.announcementinfos = announcementinfos;
       this.subjectinfos = subjectinfos;
    }
   
    public Integer getDepartmentInfoId() {
        return this.departmentInfoId;
    }
    
    public void setDepartmentInfoId(Integer departmentInfoId) {
        this.departmentInfoId = departmentInfoId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set<Userinfo> getUserinfos() {
        return this.userinfos;
    }
    
    public void setUserinfos(Set<Userinfo> userinfos) {
        this.userinfos = userinfos;
    }
    public Set<Announcementinfo> getAnnouncementinfos() {
        return this.announcementinfos;
    }
    
    public void setAnnouncementinfos(Set<Announcementinfo> announcementinfos) {
        this.announcementinfos = announcementinfos;
    }
    public Set<Subjectinfo> getSubjectinfos() {
        return this.subjectinfos;
    }
    
    public void setSubjectinfos(Set<Subjectinfo> subjectinfos) {
        this.subjectinfos = subjectinfos;
    }




}


