package com.pojos;
// Generated Nov 14, 2018 4:08:11 PM by Hibernate Tools 4.3.1



/**
 * GradingId generated by hbm2java
 */
public class GradingId  implements java.io.Serializable {


     private int subjectInfoId;
     private String studentCitizenshipNumber;

    public GradingId() {
    }

    public GradingId(int subjectInfoId, String studentCitizenshipNumber) {
       this.subjectInfoId = subjectInfoId;
       this.studentCitizenshipNumber = studentCitizenshipNumber;
    }
   
    public int getSubjectInfoId() {
        return this.subjectInfoId;
    }
    
    public void setSubjectInfoId(int subjectInfoId) {
        this.subjectInfoId = subjectInfoId;
    }
    public String getStudentCitizenshipNumber() {
        return this.studentCitizenshipNumber;
    }
    
    public void setStudentCitizenshipNumber(String studentCitizenshipNumber) {
        this.studentCitizenshipNumber = studentCitizenshipNumber;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GradingId) ) return false;
		 GradingId castOther = ( GradingId ) other; 
         
		 return (this.getSubjectInfoId()==castOther.getSubjectInfoId())
 && ( (this.getStudentCitizenshipNumber()==castOther.getStudentCitizenshipNumber()) || ( this.getStudentCitizenshipNumber()!=null && castOther.getStudentCitizenshipNumber()!=null && this.getStudentCitizenshipNumber().equals(castOther.getStudentCitizenshipNumber()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSubjectInfoId();
         result = 37 * result + ( getStudentCitizenshipNumber() == null ? 0 : this.getStudentCitizenshipNumber().hashCode() );
         return result;
   }   


}


