package com.pojos;
// Generated Nov 14, 2018 4:08:11 PM by Hibernate Tools 4.3.1



/**
 * Runtimeproperties generated by hbm2java
 */
public class Runtimeproperties  implements java.io.Serializable {


     private Integer propertyId;
     private String courseRegistrationStatus;

    public Runtimeproperties() {
    }

    public Runtimeproperties(String courseRegistrationStatus) {
       this.courseRegistrationStatus = courseRegistrationStatus;
    }
   
    public Integer getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(Integer propertyId) {
        this.propertyId = propertyId;
    }
    public String getCourseRegistrationStatus() {
        return this.courseRegistrationStatus;
    }
    
    public void setCourseRegistrationStatus(String courseRegistrationStatus) {
        this.courseRegistrationStatus = courseRegistrationStatus;
    }




}


