package com.pojos;
// Generated Nov 14, 2018 4:08:11 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subjectinfo generated by hbm2java
 */
public class Subjectinfo  implements java.io.Serializable {


     private Integer subjectInfoId;
     private Departmentinfo departmentinfo;
     private Userinfo userinfo;
     private String name;
     private int quota;
     private String year;
     private String season;
     private String isActive;
     private Set<Grading> gradings = new HashSet<Grading>(0);

    public Subjectinfo() {
    }

	
    public Subjectinfo(Departmentinfo departmentinfo, Userinfo userinfo, String name, int quota, String year, String season, String isActive) {
        this.departmentinfo = departmentinfo;
        this.userinfo = userinfo;
        this.name = name;
        this.quota = quota;
        this.year = year;
        this.season = season;
        this.isActive = isActive;
    }
    public Subjectinfo(Departmentinfo departmentinfo, Userinfo userinfo, String name, int quota, String year, String season, String isActive, Set<Grading> gradings) {
       this.departmentinfo = departmentinfo;
       this.userinfo = userinfo;
       this.name = name;
       this.quota = quota;
       this.year = year;
       this.season = season;
       this.isActive = isActive;
       this.gradings = gradings;
    }
   
    public Integer getSubjectInfoId() {
        return this.subjectInfoId;
    }
    
    public void setSubjectInfoId(Integer subjectInfoId) {
        this.subjectInfoId = subjectInfoId;
    }
    public Departmentinfo getDepartmentinfo() {
        return this.departmentinfo;
    }
    
    public void setDepartmentinfo(Departmentinfo departmentinfo) {
        this.departmentinfo = departmentinfo;
    }
    public Userinfo getUserinfo() {
        return this.userinfo;
    }
    
    public void setUserinfo(Userinfo userinfo) {
        this.userinfo = userinfo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getQuota() {
        return this.quota;
    }
    
    public void setQuota(int quota) {
        this.quota = quota;
    }
    public String getYear() {
        return this.year;
    }
    
    public void setYear(String year) {
        this.year = year;
    }
    public String getSeason() {
        return this.season;
    }
    
    public void setSeason(String season) {
        this.season = season;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Set<Grading> getGradings() {
        return this.gradings;
    }
    
    public void setGradings(Set<Grading> gradings) {
        this.gradings = gradings;
    }




}


