package com.pojos;
// Generated Nov 14, 2018 4:08:11 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Userinfo generated by hbm2java
 */
public class Userinfo  implements java.io.Serializable {


     private String citizenshipNumber;
     private Departmentinfo departmentinfo;
     private String userType;
     private String firstName;
     private String middleName;
     private String lastName;
     private String gender;
     private String email;
     private String password;
     private Date dateOfBirth;
     private String remark;
     private String isActive;
     private Set<Subjectinfo> subjectinfos = new HashSet<Subjectinfo>(0);
     private Set<Grading> gradings = new HashSet<Grading>(0);
     private Set<Announcementinfo> announcementinfos = new HashSet<Announcementinfo>(0);

    public Userinfo() {
    }

	
    public Userinfo(String citizenshipNumber, Departmentinfo departmentinfo, String userType, String firstName, String lastName, String gender, String email, String password, Date dateOfBirth, String remark, String isActive) {
        this.citizenshipNumber = citizenshipNumber;
        this.departmentinfo = departmentinfo;
        this.userType = userType;
        this.firstName = firstName;
        this.lastName = lastName;
        this.gender = gender;
        this.email = email;
        this.password = password;
        this.dateOfBirth = dateOfBirth;
        this.remark = remark;
        this.isActive = isActive;
    }
    public Userinfo(String citizenshipNumber, Departmentinfo departmentinfo, String userType, String firstName, String middleName, String lastName, String gender, String email, String password, Date dateOfBirth, String remark, String isActive, Set<Subjectinfo> subjectinfos, Set<Grading> gradings, Set<Announcementinfo> announcementinfos) {
       this.citizenshipNumber = citizenshipNumber;
       this.departmentinfo = departmentinfo;
       this.userType = userType;
       this.firstName = firstName;
       this.middleName = middleName;
       this.lastName = lastName;
       this.gender = gender;
       this.email = email;
       this.password = password;
       this.dateOfBirth = dateOfBirth;
       this.remark = remark;
       this.isActive = isActive;
       this.subjectinfos = subjectinfos;
       this.gradings = gradings;
       this.announcementinfos = announcementinfos;
    }
   
    public String getCitizenshipNumber() {
        return this.citizenshipNumber;
    }
    
    public void setCitizenshipNumber(String citizenshipNumber) {
        this.citizenshipNumber = citizenshipNumber;
    }
    public Departmentinfo getDepartmentinfo() {
        return this.departmentinfo;
    }
    
    public void setDepartmentinfo(Departmentinfo departmentinfo) {
        this.departmentinfo = departmentinfo;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getMiddleName() {
        return this.middleName;
    }
    
    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getRemark() {
        return this.remark;
    }
    
    public void setRemark(String remark) {
        this.remark = remark;
    }
    public String getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(String isActive) {
        this.isActive = isActive;
    }
    public Set<Subjectinfo> getSubjectinfos() {
        return this.subjectinfos;
    }
    
    public void setSubjectinfos(Set<Subjectinfo> subjectinfos) {
        this.subjectinfos = subjectinfos;
    }
    public Set<Grading> getGradings() {
        return this.gradings;
    }
    
    public void setGradings(Set<Grading> gradings) {
        this.gradings = gradings;
    }
    public Set<Announcementinfo> getAnnouncementinfos() {
        return this.announcementinfos;
    }
    
    public void setAnnouncementinfos(Set<Announcementinfo> announcementinfos) {
        this.announcementinfos = announcementinfos;
    }




}


